// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"math/big"
	"sync"

	"github.com/LFDT-Panurus/panurus/token/driver"
	"github.com/LFDT-Panurus/panurus/token/services/identity/role"
	"github.com/LFDT-Panurus/panurus/token/token"
)

type IssuerTokenVault struct {
	IssuedBalanceStub        func(context.Context, driver.IssuerBalanceQuery) (*big.Int, error)
	issuedBalanceMutex       sync.RWMutex
	issuedBalanceArgsForCall []struct {
		arg1 context.Context
		arg2 driver.IssuerBalanceQuery
	}
	issuedBalanceReturns struct {
		result1 *big.Int
		result2 error
	}
	issuedBalanceReturnsOnCall map[int]struct {
		result1 *big.Int
		result2 error
	}
	ListHistoryIssuedTokensStub        func(context.Context) (*token.IssuedTokens, error)
	listHistoryIssuedTokensMutex       sync.RWMutex
	listHistoryIssuedTokensArgsForCall []struct {
		arg1 context.Context
	}
	listHistoryIssuedTokensReturns struct {
		result1 *token.IssuedTokens
		result2 error
	}
	listHistoryIssuedTokensReturnsOnCall map[int]struct {
		result1 *token.IssuedTokens
		result2 error
	}
	RedeemedBalanceStub        func(context.Context, driver.IssuerBalanceQuery) (*big.Int, error)
	redeemedBalanceMutex       sync.RWMutex
	redeemedBalanceArgsForCall []struct {
		arg1 context.Context
		arg2 driver.IssuerBalanceQuery
	}
	redeemedBalanceReturns struct {
		result1 *big.Int
		result2 error
	}
	redeemedBalanceReturnsOnCall map[int]struct {
		result1 *big.Int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *IssuerTokenVault) IssuedBalance(arg1 context.Context, arg2 driver.IssuerBalanceQuery) (*big.Int, error) {
	fake.issuedBalanceMutex.Lock()
	ret, specificReturn := fake.issuedBalanceReturnsOnCall[len(fake.issuedBalanceArgsForCall)]
	fake.issuedBalanceArgsForCall = append(fake.issuedBalanceArgsForCall, struct {
		arg1 context.Context
		arg2 driver.IssuerBalanceQuery
	}{arg1, arg2})
	stub := fake.IssuedBalanceStub
	fakeReturns := fake.issuedBalanceReturns
	fake.recordInvocation("IssuedBalance", []interface{}{arg1, arg2})
	fake.issuedBalanceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IssuerTokenVault) IssuedBalanceCallCount() int {
	fake.issuedBalanceMutex.RLock()
	defer fake.issuedBalanceMutex.RUnlock()
	return len(fake.issuedBalanceArgsForCall)
}

func (fake *IssuerTokenVault) IssuedBalanceCalls(stub func(context.Context, driver.IssuerBalanceQuery) (*big.Int, error)) {
	fake.issuedBalanceMutex.Lock()
	defer fake.issuedBalanceMutex.Unlock()
	fake.IssuedBalanceStub = stub
}

func (fake *IssuerTokenVault) IssuedBalanceArgsForCall(i int) (context.Context, driver.IssuerBalanceQuery) {
	fake.issuedBalanceMutex.RLock()
	defer fake.issuedBalanceMutex.RUnlock()
	argsForCall := fake.issuedBalanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IssuerTokenVault) IssuedBalanceReturns(result1 *big.Int, result2 error) {
	fake.issuedBalanceMutex.Lock()
	defer fake.issuedBalanceMutex.Unlock()
	fake.IssuedBalanceStub = nil
	fake.issuedBalanceReturns = struct {
		result1 *big.Int
		result2 error
	}{result1, result2}
}

func (fake *IssuerTokenVault) IssuedBalanceReturnsOnCall(i int, result1 *big.Int, result2 error) {
	fake.issuedBalanceMutex.Lock()
	defer fake.issuedBalanceMutex.Unlock()
	fake.IssuedBalanceStub = nil
	if fake.issuedBalanceReturnsOnCall == nil {
		fake.issuedBalanceReturnsOnCall = make(map[int]struct {
			result1 *big.Int
			result2 error
		})
	}
	fake.issuedBalanceReturnsOnCall[i] = struct {
		result1 *big.Int
		result2 error
	}{result1, result2}
}

func (fake *IssuerTokenVault) ListHistoryIssuedTokens(arg1 context.Context) (*token.IssuedTokens, error) {
	fake.listHistoryIssuedTokensMutex.Lock()
	ret, specificReturn := fake.listHistoryIssuedTokensReturnsOnCall[len(fake.listHistoryIssuedTokensArgsForCall)]
	fake.listHistoryIssuedTokensArgsForCall = append(fake.listHistoryIssuedTokensArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListHistoryIssuedTokensStub
	fakeReturns := fake.listHistoryIssuedTokensReturns
	fake.recordInvocation("ListHistoryIssuedTokens", []interface{}{arg1})
	fake.listHistoryIssuedTokensMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IssuerTokenVault) ListHistoryIssuedTokensCallCount() int {
	fake.listHistoryIssuedTokensMutex.RLock()
	defer fake.listHistoryIssuedTokensMutex.RUnlock()
	return len(fake.listHistoryIssuedTokensArgsForCall)
}

func (fake *IssuerTokenVault) ListHistoryIssuedTokensCalls(stub func(context.Context) (*token.IssuedTokens, error)) {
	fake.listHistoryIssuedTokensMutex.Lock()
	defer fake.listHistoryIssuedTokensMutex.Unlock()
	fake.ListHistoryIssuedTokensStub = stub
}

func (fake *IssuerTokenVault) ListHistoryIssuedTokensArgsForCall(i int) context.Context {
	fake.listHistoryIssuedTokensMutex.RLock()
	defer fake.listHistoryIssuedTokensMutex.RUnlock()
	argsForCall := fake.listHistoryIssuedTokensArgsForCall[i]
	return argsForCall.arg1
}

func (fake *IssuerTokenVault) ListHistoryIssuedTokensReturns(result1 *token.IssuedTokens, result2 error) {
	fake.listHistoryIssuedTokensMutex.Lock()
	defer fake.listHistoryIssuedTokensMutex.Unlock()
	fake.ListHistoryIssuedTokensStub = nil
	fake.listHistoryIssuedTokensReturns = struct {
		result1 *token.IssuedTokens
		result2 error
	}{result1, result2}
}

func (fake *IssuerTokenVault) ListHistoryIssuedTokensReturnsOnCall(i int, result1 *token.IssuedTokens, result2 error) {
	fake.listHistoryIssuedTokensMutex.Lock()
	defer fake.listHistoryIssuedTokensMutex.Unlock()
	fake.ListHistoryIssuedTokensStub = nil
	if fake.listHistoryIssuedTokensReturnsOnCall == nil {
		fake.listHistoryIssuedTokensReturnsOnCall = make(map[int]struct {
			result1 *token.IssuedTokens
			result2 error
		})
	}
	fake.listHistoryIssuedTokensReturnsOnCall[i] = struct {
		result1 *token.IssuedTokens
		result2 error
	}{result1, result2}
}

func (fake *IssuerTokenVault) RedeemedBalance(arg1 context.Context, arg2 driver.IssuerBalanceQuery) (*big.Int, error) {
	fake.redeemedBalanceMutex.Lock()
	ret, specificReturn := fake.redeemedBalanceReturnsOnCall[len(fake.redeemedBalanceArgsForCall)]
	fake.redeemedBalanceArgsForCall = append(fake.redeemedBalanceArgsForCall, struct {
		arg1 context.Context
		arg2 driver.IssuerBalanceQuery
	}{arg1, arg2})
	stub := fake.RedeemedBalanceStub
	fakeReturns := fake.redeemedBalanceReturns
	fake.recordInvocation("RedeemedBalance", []interface{}{arg1, arg2})
	fake.redeemedBalanceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *IssuerTokenVault) RedeemedBalanceCallCount() int {
	fake.redeemedBalanceMutex.RLock()
	defer fake.redeemedBalanceMutex.RUnlock()
	return len(fake.redeemedBalanceArgsForCall)
}

func (fake *IssuerTokenVault) RedeemedBalanceCalls(stub func(context.Context, driver.IssuerBalanceQuery) (*big.Int, error)) {
	fake.redeemedBalanceMutex.Lock()
	defer fake.redeemedBalanceMutex.Unlock()
	fake.RedeemedBalanceStub = stub
}

func (fake *IssuerTokenVault) RedeemedBalanceArgsForCall(i int) (context.Context, driver.IssuerBalanceQuery) {
	fake.redeemedBalanceMutex.RLock()
	defer fake.redeemedBalanceMutex.RUnlock()
	argsForCall := fake.redeemedBalanceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *IssuerTokenVault) RedeemedBalanceReturns(result1 *big.Int, result2 error) {
	fake.redeemedBalanceMutex.Lock()
	defer fake.redeemedBalanceMutex.Unlock()
	fake.RedeemedBalanceStub = nil
	fake.redeemedBalanceReturns = struct {
		result1 *big.Int
		result2 error
	}{result1, result2}
}

func (fake *IssuerTokenVault) RedeemedBalanceReturnsOnCall(i int, result1 *big.Int, result2 error) {
	fake.redeemedBalanceMutex.Lock()
	defer fake.redeemedBalanceMutex.Unlock()
	fake.RedeemedBalanceStub = nil
	if fake.redeemedBalanceReturnsOnCall == nil {
		fake.redeemedBalanceReturnsOnCall = make(map[int]struct {
			result1 *big.Int
			result2 error
		})
	}
	fake.redeemedBalanceReturnsOnCall[i] = struct {
		result1 *big.Int
		result2 error
	}{result1, result2}
}

func (fake *IssuerTokenVault) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *IssuerTokenVault) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ role.IssuerTokenVault = new(IssuerTokenVault)
