// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"context"
	"math/big"
	"sync"

	"github.com/LFDT-Panurus/panurus/x/token/services/network/evm/client"
)

type EVMClient struct {
	CallStub        func(context.Context, client.Address, []byte, string) ([]byte, error)
	callMutex       sync.RWMutex
	callArgsForCall []struct {
		arg1 context.Context
		arg2 client.Address
		arg3 []byte
		arg4 string
	}
	callReturns struct {
		result1 []byte
		result2 error
	}
	callReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	ChainIDStub        func(context.Context) (*big.Int, error)
	chainIDMutex       sync.RWMutex
	chainIDArgsForCall []struct {
		arg1 context.Context
	}
	chainIDReturns struct {
		result1 *big.Int
		result2 error
	}
	chainIDReturnsOnCall map[int]struct {
		result1 *big.Int
		result2 error
	}
	EstimateGasStub        func(context.Context, client.CallMsg) (uint64, error)
	estimateGasMutex       sync.RWMutex
	estimateGasArgsForCall []struct {
		arg1 context.Context
		arg2 client.CallMsg
	}
	estimateGasReturns struct {
		result1 uint64
		result2 error
	}
	estimateGasReturnsOnCall map[int]struct {
		result1 uint64
		result2 error
	}
	GetLogsStub        func(context.Context, client.LogFilter) ([]client.Log, error)
	getLogsMutex       sync.RWMutex
	getLogsArgsForCall []struct {
		arg1 context.Context
		arg2 client.LogFilter
	}
	getLogsReturns struct {
		result1 []client.Log
		result2 error
	}
	getLogsReturnsOnCall map[int]struct {
		result1 []client.Log
		result2 error
	}
	GetTransactionReceiptStub        func(context.Context, client.Hash) (*client.Receipt, error)
	getTransactionReceiptMutex       sync.RWMutex
	getTransactionReceiptArgsForCall []struct {
		arg1 context.Context
		arg2 client.Hash
	}
	getTransactionReceiptReturns struct {
		result1 *client.Receipt
		result2 error
	}
	getTransactionReceiptReturnsOnCall map[int]struct {
		result1 *client.Receipt
		result2 error
	}
	IsPendingStub        func(context.Context, client.Hash) (bool, bool, error)
	isPendingMutex       sync.RWMutex
	isPendingArgsForCall []struct {
		arg1 context.Context
		arg2 client.Hash
	}
	isPendingReturns struct {
		result1 bool
		result2 bool
		result3 error
	}
	isPendingReturnsOnCall map[int]struct {
		result1 bool
		result2 bool
		result3 error
	}
	PendingNonceAtStub        func(context.Context, client.Address) (uint64, error)
	pendingNonceAtMutex       sync.RWMutex
	pendingNonceAtArgsForCall []struct {
		arg1 context.Context
		arg2 client.Address
	}
	pendingNonceAtReturns struct {
		result1 uint64
		result2 error
	}
	pendingNonceAtReturnsOnCall map[int]struct {
		result1 uint64
		result2 error
	}
	PingStub        func(context.Context) error
	pingMutex       sync.RWMutex
	pingArgsForCall []struct {
		arg1 context.Context
	}
	pingReturns struct {
		result1 error
	}
	pingReturnsOnCall map[int]struct {
		result1 error
	}
	SendRawTransactionStub        func(context.Context, []byte) (client.Hash, error)
	sendRawTransactionMutex       sync.RWMutex
	sendRawTransactionArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	sendRawTransactionReturns struct {
		result1 client.Hash
		result2 error
	}
	sendRawTransactionReturnsOnCall map[int]struct {
		result1 client.Hash
		result2 error
	}
	SuggestGasFeesStub        func(context.Context) (client.GasFees, error)
	suggestGasFeesMutex       sync.RWMutex
	suggestGasFeesArgsForCall []struct {
		arg1 context.Context
	}
	suggestGasFeesReturns struct {
		result1 client.GasFees
		result2 error
	}
	suggestGasFeesReturnsOnCall map[int]struct {
		result1 client.GasFees
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *EVMClient) Call(arg1 context.Context, arg2 client.Address, arg3 []byte, arg4 string) ([]byte, error) {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.callMutex.Lock()
	ret, specificReturn := fake.callReturnsOnCall[len(fake.callArgsForCall)]
	fake.callArgsForCall = append(fake.callArgsForCall, struct {
		arg1 context.Context
		arg2 client.Address
		arg3 []byte
		arg4 string
	}{arg1, arg2, arg3Copy, arg4})
	stub := fake.CallStub
	fakeReturns := fake.callReturns
	fake.recordInvocation("Call", []interface{}{arg1, arg2, arg3Copy, arg4})
	fake.callMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) CallCallCount() int {
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	return len(fake.callArgsForCall)
}

func (fake *EVMClient) CallCalls(stub func(context.Context, client.Address, []byte, string) ([]byte, error)) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = stub
}

func (fake *EVMClient) CallArgsForCall(i int) (context.Context, client.Address, []byte, string) {
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	argsForCall := fake.callArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *EVMClient) CallReturns(result1 []byte, result2 error) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = nil
	fake.callReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) CallReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = nil
	if fake.callReturnsOnCall == nil {
		fake.callReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.callReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) ChainID(arg1 context.Context) (*big.Int, error) {
	fake.chainIDMutex.Lock()
	ret, specificReturn := fake.chainIDReturnsOnCall[len(fake.chainIDArgsForCall)]
	fake.chainIDArgsForCall = append(fake.chainIDArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ChainIDStub
	fakeReturns := fake.chainIDReturns
	fake.recordInvocation("ChainID", []interface{}{arg1})
	fake.chainIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) ChainIDCallCount() int {
	fake.chainIDMutex.RLock()
	defer fake.chainIDMutex.RUnlock()
	return len(fake.chainIDArgsForCall)
}

func (fake *EVMClient) ChainIDCalls(stub func(context.Context) (*big.Int, error)) {
	fake.chainIDMutex.Lock()
	defer fake.chainIDMutex.Unlock()
	fake.ChainIDStub = stub
}

func (fake *EVMClient) ChainIDArgsForCall(i int) context.Context {
	fake.chainIDMutex.RLock()
	defer fake.chainIDMutex.RUnlock()
	argsForCall := fake.chainIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *EVMClient) ChainIDReturns(result1 *big.Int, result2 error) {
	fake.chainIDMutex.Lock()
	defer fake.chainIDMutex.Unlock()
	fake.ChainIDStub = nil
	fake.chainIDReturns = struct {
		result1 *big.Int
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) ChainIDReturnsOnCall(i int, result1 *big.Int, result2 error) {
	fake.chainIDMutex.Lock()
	defer fake.chainIDMutex.Unlock()
	fake.ChainIDStub = nil
	if fake.chainIDReturnsOnCall == nil {
		fake.chainIDReturnsOnCall = make(map[int]struct {
			result1 *big.Int
			result2 error
		})
	}
	fake.chainIDReturnsOnCall[i] = struct {
		result1 *big.Int
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) EstimateGas(arg1 context.Context, arg2 client.CallMsg) (uint64, error) {
	fake.estimateGasMutex.Lock()
	ret, specificReturn := fake.estimateGasReturnsOnCall[len(fake.estimateGasArgsForCall)]
	fake.estimateGasArgsForCall = append(fake.estimateGasArgsForCall, struct {
		arg1 context.Context
		arg2 client.CallMsg
	}{arg1, arg2})
	stub := fake.EstimateGasStub
	fakeReturns := fake.estimateGasReturns
	fake.recordInvocation("EstimateGas", []interface{}{arg1, arg2})
	fake.estimateGasMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) EstimateGasCallCount() int {
	fake.estimateGasMutex.RLock()
	defer fake.estimateGasMutex.RUnlock()
	return len(fake.estimateGasArgsForCall)
}

func (fake *EVMClient) EstimateGasCalls(stub func(context.Context, client.CallMsg) (uint64, error)) {
	fake.estimateGasMutex.Lock()
	defer fake.estimateGasMutex.Unlock()
	fake.EstimateGasStub = stub
}

func (fake *EVMClient) EstimateGasArgsForCall(i int) (context.Context, client.CallMsg) {
	fake.estimateGasMutex.RLock()
	defer fake.estimateGasMutex.RUnlock()
	argsForCall := fake.estimateGasArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *EVMClient) EstimateGasReturns(result1 uint64, result2 error) {
	fake.estimateGasMutex.Lock()
	defer fake.estimateGasMutex.Unlock()
	fake.EstimateGasStub = nil
	fake.estimateGasReturns = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) EstimateGasReturnsOnCall(i int, result1 uint64, result2 error) {
	fake.estimateGasMutex.Lock()
	defer fake.estimateGasMutex.Unlock()
	fake.EstimateGasStub = nil
	if fake.estimateGasReturnsOnCall == nil {
		fake.estimateGasReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 error
		})
	}
	fake.estimateGasReturnsOnCall[i] = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) GetLogs(arg1 context.Context, arg2 client.LogFilter) ([]client.Log, error) {
	fake.getLogsMutex.Lock()
	ret, specificReturn := fake.getLogsReturnsOnCall[len(fake.getLogsArgsForCall)]
	fake.getLogsArgsForCall = append(fake.getLogsArgsForCall, struct {
		arg1 context.Context
		arg2 client.LogFilter
	}{arg1, arg2})
	stub := fake.GetLogsStub
	fakeReturns := fake.getLogsReturns
	fake.recordInvocation("GetLogs", []interface{}{arg1, arg2})
	fake.getLogsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) GetLogsCallCount() int {
	fake.getLogsMutex.RLock()
	defer fake.getLogsMutex.RUnlock()
	return len(fake.getLogsArgsForCall)
}

func (fake *EVMClient) GetLogsCalls(stub func(context.Context, client.LogFilter) ([]client.Log, error)) {
	fake.getLogsMutex.Lock()
	defer fake.getLogsMutex.Unlock()
	fake.GetLogsStub = stub
}

func (fake *EVMClient) GetLogsArgsForCall(i int) (context.Context, client.LogFilter) {
	fake.getLogsMutex.RLock()
	defer fake.getLogsMutex.RUnlock()
	argsForCall := fake.getLogsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *EVMClient) GetLogsReturns(result1 []client.Log, result2 error) {
	fake.getLogsMutex.Lock()
	defer fake.getLogsMutex.Unlock()
	fake.GetLogsStub = nil
	fake.getLogsReturns = struct {
		result1 []client.Log
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) GetLogsReturnsOnCall(i int, result1 []client.Log, result2 error) {
	fake.getLogsMutex.Lock()
	defer fake.getLogsMutex.Unlock()
	fake.GetLogsStub = nil
	if fake.getLogsReturnsOnCall == nil {
		fake.getLogsReturnsOnCall = make(map[int]struct {
			result1 []client.Log
			result2 error
		})
	}
	fake.getLogsReturnsOnCall[i] = struct {
		result1 []client.Log
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) GetTransactionReceipt(arg1 context.Context, arg2 client.Hash) (*client.Receipt, error) {
	fake.getTransactionReceiptMutex.Lock()
	ret, specificReturn := fake.getTransactionReceiptReturnsOnCall[len(fake.getTransactionReceiptArgsForCall)]
	fake.getTransactionReceiptArgsForCall = append(fake.getTransactionReceiptArgsForCall, struct {
		arg1 context.Context
		arg2 client.Hash
	}{arg1, arg2})
	stub := fake.GetTransactionReceiptStub
	fakeReturns := fake.getTransactionReceiptReturns
	fake.recordInvocation("GetTransactionReceipt", []interface{}{arg1, arg2})
	fake.getTransactionReceiptMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) GetTransactionReceiptCallCount() int {
	fake.getTransactionReceiptMutex.RLock()
	defer fake.getTransactionReceiptMutex.RUnlock()
	return len(fake.getTransactionReceiptArgsForCall)
}

func (fake *EVMClient) GetTransactionReceiptCalls(stub func(context.Context, client.Hash) (*client.Receipt, error)) {
	fake.getTransactionReceiptMutex.Lock()
	defer fake.getTransactionReceiptMutex.Unlock()
	fake.GetTransactionReceiptStub = stub
}

func (fake *EVMClient) GetTransactionReceiptArgsForCall(i int) (context.Context, client.Hash) {
	fake.getTransactionReceiptMutex.RLock()
	defer fake.getTransactionReceiptMutex.RUnlock()
	argsForCall := fake.getTransactionReceiptArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *EVMClient) GetTransactionReceiptReturns(result1 *client.Receipt, result2 error) {
	fake.getTransactionReceiptMutex.Lock()
	defer fake.getTransactionReceiptMutex.Unlock()
	fake.GetTransactionReceiptStub = nil
	fake.getTransactionReceiptReturns = struct {
		result1 *client.Receipt
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) GetTransactionReceiptReturnsOnCall(i int, result1 *client.Receipt, result2 error) {
	fake.getTransactionReceiptMutex.Lock()
	defer fake.getTransactionReceiptMutex.Unlock()
	fake.GetTransactionReceiptStub = nil
	if fake.getTransactionReceiptReturnsOnCall == nil {
		fake.getTransactionReceiptReturnsOnCall = make(map[int]struct {
			result1 *client.Receipt
			result2 error
		})
	}
	fake.getTransactionReceiptReturnsOnCall[i] = struct {
		result1 *client.Receipt
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) IsPending(arg1 context.Context, arg2 client.Hash) (bool, bool, error) {
	fake.isPendingMutex.Lock()
	ret, specificReturn := fake.isPendingReturnsOnCall[len(fake.isPendingArgsForCall)]
	fake.isPendingArgsForCall = append(fake.isPendingArgsForCall, struct {
		arg1 context.Context
		arg2 client.Hash
	}{arg1, arg2})
	stub := fake.IsPendingStub
	fakeReturns := fake.isPendingReturns
	fake.recordInvocation("IsPending", []interface{}{arg1, arg2})
	fake.isPendingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *EVMClient) IsPendingCallCount() int {
	fake.isPendingMutex.RLock()
	defer fake.isPendingMutex.RUnlock()
	return len(fake.isPendingArgsForCall)
}

func (fake *EVMClient) IsPendingCalls(stub func(context.Context, client.Hash) (bool, bool, error)) {
	fake.isPendingMutex.Lock()
	defer fake.isPendingMutex.Unlock()
	fake.IsPendingStub = stub
}

func (fake *EVMClient) IsPendingArgsForCall(i int) (context.Context, client.Hash) {
	fake.isPendingMutex.RLock()
	defer fake.isPendingMutex.RUnlock()
	argsForCall := fake.isPendingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *EVMClient) IsPendingReturns(result1 bool, result2 bool, result3 error) {
	fake.isPendingMutex.Lock()
	defer fake.isPendingMutex.Unlock()
	fake.IsPendingStub = nil
	fake.isPendingReturns = struct {
		result1 bool
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *EVMClient) IsPendingReturnsOnCall(i int, result1 bool, result2 bool, result3 error) {
	fake.isPendingMutex.Lock()
	defer fake.isPendingMutex.Unlock()
	fake.IsPendingStub = nil
	if fake.isPendingReturnsOnCall == nil {
		fake.isPendingReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 bool
			result3 error
		})
	}
	fake.isPendingReturnsOnCall[i] = struct {
		result1 bool
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *EVMClient) PendingNonceAt(arg1 context.Context, arg2 client.Address) (uint64, error) {
	fake.pendingNonceAtMutex.Lock()
	ret, specificReturn := fake.pendingNonceAtReturnsOnCall[len(fake.pendingNonceAtArgsForCall)]
	fake.pendingNonceAtArgsForCall = append(fake.pendingNonceAtArgsForCall, struct {
		arg1 context.Context
		arg2 client.Address
	}{arg1, arg2})
	stub := fake.PendingNonceAtStub
	fakeReturns := fake.pendingNonceAtReturns
	fake.recordInvocation("PendingNonceAt", []interface{}{arg1, arg2})
	fake.pendingNonceAtMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) PendingNonceAtCallCount() int {
	fake.pendingNonceAtMutex.RLock()
	defer fake.pendingNonceAtMutex.RUnlock()
	return len(fake.pendingNonceAtArgsForCall)
}

func (fake *EVMClient) PendingNonceAtCalls(stub func(context.Context, client.Address) (uint64, error)) {
	fake.pendingNonceAtMutex.Lock()
	defer fake.pendingNonceAtMutex.Unlock()
	fake.PendingNonceAtStub = stub
}

func (fake *EVMClient) PendingNonceAtArgsForCall(i int) (context.Context, client.Address) {
	fake.pendingNonceAtMutex.RLock()
	defer fake.pendingNonceAtMutex.RUnlock()
	argsForCall := fake.pendingNonceAtArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *EVMClient) PendingNonceAtReturns(result1 uint64, result2 error) {
	fake.pendingNonceAtMutex.Lock()
	defer fake.pendingNonceAtMutex.Unlock()
	fake.PendingNonceAtStub = nil
	fake.pendingNonceAtReturns = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) PendingNonceAtReturnsOnCall(i int, result1 uint64, result2 error) {
	fake.pendingNonceAtMutex.Lock()
	defer fake.pendingNonceAtMutex.Unlock()
	fake.PendingNonceAtStub = nil
	if fake.pendingNonceAtReturnsOnCall == nil {
		fake.pendingNonceAtReturnsOnCall = make(map[int]struct {
			result1 uint64
			result2 error
		})
	}
	fake.pendingNonceAtReturnsOnCall[i] = struct {
		result1 uint64
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) Ping(arg1 context.Context) error {
	fake.pingMutex.Lock()
	ret, specificReturn := fake.pingReturnsOnCall[len(fake.pingArgsForCall)]
	fake.pingArgsForCall = append(fake.pingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PingStub
	fakeReturns := fake.pingReturns
	fake.recordInvocation("Ping", []interface{}{arg1})
	fake.pingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *EVMClient) PingCallCount() int {
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	return len(fake.pingArgsForCall)
}

func (fake *EVMClient) PingCalls(stub func(context.Context) error) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = stub
}

func (fake *EVMClient) PingArgsForCall(i int) context.Context {
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	argsForCall := fake.pingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *EVMClient) PingReturns(result1 error) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = nil
	fake.pingReturns = struct {
		result1 error
	}{result1}
}

func (fake *EVMClient) PingReturnsOnCall(i int, result1 error) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = nil
	if fake.pingReturnsOnCall == nil {
		fake.pingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *EVMClient) SendRawTransaction(arg1 context.Context, arg2 []byte) (client.Hash, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.sendRawTransactionMutex.Lock()
	ret, specificReturn := fake.sendRawTransactionReturnsOnCall[len(fake.sendRawTransactionArgsForCall)]
	fake.sendRawTransactionArgsForCall = append(fake.sendRawTransactionArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.SendRawTransactionStub
	fakeReturns := fake.sendRawTransactionReturns
	fake.recordInvocation("SendRawTransaction", []interface{}{arg1, arg2Copy})
	fake.sendRawTransactionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) SendRawTransactionCallCount() int {
	fake.sendRawTransactionMutex.RLock()
	defer fake.sendRawTransactionMutex.RUnlock()
	return len(fake.sendRawTransactionArgsForCall)
}

func (fake *EVMClient) SendRawTransactionCalls(stub func(context.Context, []byte) (client.Hash, error)) {
	fake.sendRawTransactionMutex.Lock()
	defer fake.sendRawTransactionMutex.Unlock()
	fake.SendRawTransactionStub = stub
}

func (fake *EVMClient) SendRawTransactionArgsForCall(i int) (context.Context, []byte) {
	fake.sendRawTransactionMutex.RLock()
	defer fake.sendRawTransactionMutex.RUnlock()
	argsForCall := fake.sendRawTransactionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *EVMClient) SendRawTransactionReturns(result1 client.Hash, result2 error) {
	fake.sendRawTransactionMutex.Lock()
	defer fake.sendRawTransactionMutex.Unlock()
	fake.SendRawTransactionStub = nil
	fake.sendRawTransactionReturns = struct {
		result1 client.Hash
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) SendRawTransactionReturnsOnCall(i int, result1 client.Hash, result2 error) {
	fake.sendRawTransactionMutex.Lock()
	defer fake.sendRawTransactionMutex.Unlock()
	fake.SendRawTransactionStub = nil
	if fake.sendRawTransactionReturnsOnCall == nil {
		fake.sendRawTransactionReturnsOnCall = make(map[int]struct {
			result1 client.Hash
			result2 error
		})
	}
	fake.sendRawTransactionReturnsOnCall[i] = struct {
		result1 client.Hash
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) SuggestGasFees(arg1 context.Context) (client.GasFees, error) {
	fake.suggestGasFeesMutex.Lock()
	ret, specificReturn := fake.suggestGasFeesReturnsOnCall[len(fake.suggestGasFeesArgsForCall)]
	fake.suggestGasFeesArgsForCall = append(fake.suggestGasFeesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SuggestGasFeesStub
	fakeReturns := fake.suggestGasFeesReturns
	fake.recordInvocation("SuggestGasFees", []interface{}{arg1})
	fake.suggestGasFeesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EVMClient) SuggestGasFeesCallCount() int {
	fake.suggestGasFeesMutex.RLock()
	defer fake.suggestGasFeesMutex.RUnlock()
	return len(fake.suggestGasFeesArgsForCall)
}

func (fake *EVMClient) SuggestGasFeesCalls(stub func(context.Context) (client.GasFees, error)) {
	fake.suggestGasFeesMutex.Lock()
	defer fake.suggestGasFeesMutex.Unlock()
	fake.SuggestGasFeesStub = stub
}

func (fake *EVMClient) SuggestGasFeesArgsForCall(i int) context.Context {
	fake.suggestGasFeesMutex.RLock()
	defer fake.suggestGasFeesMutex.RUnlock()
	argsForCall := fake.suggestGasFeesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *EVMClient) SuggestGasFeesReturns(result1 client.GasFees, result2 error) {
	fake.suggestGasFeesMutex.Lock()
	defer fake.suggestGasFeesMutex.Unlock()
	fake.SuggestGasFeesStub = nil
	fake.suggestGasFeesReturns = struct {
		result1 client.GasFees
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) SuggestGasFeesReturnsOnCall(i int, result1 client.GasFees, result2 error) {
	fake.suggestGasFeesMutex.Lock()
	defer fake.suggestGasFeesMutex.Unlock()
	fake.SuggestGasFeesStub = nil
	if fake.suggestGasFeesReturnsOnCall == nil {
		fake.suggestGasFeesReturnsOnCall = make(map[int]struct {
			result1 client.GasFees
			result2 error
		})
	}
	fake.suggestGasFeesReturnsOnCall[i] = struct {
		result1 client.GasFees
		result2 error
	}{result1, result2}
}

func (fake *EVMClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *EVMClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.EVMClient = new(EVMClient)
