// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/hyperledger-labs/fabric-smart-client/platform/view/view"
	"github.com/hyperledger-labs/fabric-token-sdk/token/services/certifier/interactive"
)

type ResponderRegistry struct {
	RegisterResponderStub        func(view.View, interface{}) error
	registerResponderMutex       sync.RWMutex
	registerResponderArgsForCall []struct {
		arg1 view.View
		arg2 interface{}
	}
	registerResponderReturns struct {
		result1 error
	}
	registerResponderReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ResponderRegistry) RegisterResponder(arg1 view.View, arg2 interface{}) error {
	fake.registerResponderMutex.Lock()
	ret, specificReturn := fake.registerResponderReturnsOnCall[len(fake.registerResponderArgsForCall)]
	fake.registerResponderArgsForCall = append(fake.registerResponderArgsForCall, struct {
		arg1 view.View
		arg2 interface{}
	}{arg1, arg2})
	stub := fake.RegisterResponderStub
	fakeReturns := fake.registerResponderReturns
	fake.recordInvocation("RegisterResponder", []interface{}{arg1, arg2})
	fake.registerResponderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *ResponderRegistry) RegisterResponderCallCount() int {
	fake.registerResponderMutex.RLock()
	defer fake.registerResponderMutex.RUnlock()
	return len(fake.registerResponderArgsForCall)
}

func (fake *ResponderRegistry) RegisterResponderCalls(stub func(view.View, interface{}) error) {
	fake.registerResponderMutex.Lock()
	defer fake.registerResponderMutex.Unlock()
	fake.RegisterResponderStub = stub
}

func (fake *ResponderRegistry) RegisterResponderArgsForCall(i int) (view.View, interface{}) {
	fake.registerResponderMutex.RLock()
	defer fake.registerResponderMutex.RUnlock()
	argsForCall := fake.registerResponderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ResponderRegistry) RegisterResponderReturns(result1 error) {
	fake.registerResponderMutex.Lock()
	defer fake.registerResponderMutex.Unlock()
	fake.RegisterResponderStub = nil
	fake.registerResponderReturns = struct {
		result1 error
	}{result1}
}

func (fake *ResponderRegistry) RegisterResponderReturnsOnCall(i int, result1 error) {
	fake.registerResponderMutex.Lock()
	defer fake.registerResponderMutex.Unlock()
	fake.RegisterResponderStub = nil
	if fake.registerResponderReturnsOnCall == nil {
		fake.registerResponderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.registerResponderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ResponderRegistry) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ResponderRegistry) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ interactive.ResponderRegistry = new(ResponderRegistry)
